/*
 * Copyright (C) 2016 AI
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.jevis.hddparser;


import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * @author Gerrit Schutz
 */
public class DWDHDDDataPoint {
    public static String NAME = "DWD HDD Data Point";
    Map<String, String> HDD_OPTIONS = Collections.unmodifiableMap(new HashMap<String, String>() {
        {
            put(DWDHDDDataPoint.DWDHDDDataPointAttribute.STATION, "STATION");
        }
    });
    private String station;
    private String target;

    public String getStation() {
        return station;
    }

    public void setStation(String station) {
        this.station = station;
    }

    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    interface DWDDataPointsDirectory {
        String NAME = "DWD Data Point Directory";
    }

    interface DWDHDDDataPointAttribute {
        String STATION = "Station";
        String HEATING_DEGREE_DAYS = "Heating Degree Days Target";
    }

    /**
     * Station Names:
     *
     * GROSSENKNETEN
     * ALDERSBACH-KRIESTORF
     * ALFHAUSEN
     * ALSFELD-EIFA
     * NEURUPPIN-ALT RUPPIN
     * ALTE WESER (AWST)
     * ALTENSTADT (BW)
     * ALTGERINGSWALDE
     * ALTOMUENSTER-MAISBRUNN
     * ALZEY
     * AMBERG-UNTERAMMERSRICHT
     * AMERANG-PFAFFING
     * ANDERNACH
     * ANGERMUENDE (WEWA)
     * ANKLAM
     * ARKONA (WEWA)
     * ARNSTEIN-MUEDESHEIM
     * ARTERN (WEWA)
     * ATTENKAM
     * AUE
     * AUGSBURG-MUEHLH. (WEWA)
     * BADEN-BADEN-GEROLDSAU
     * MUELLHEIM
     * BAMBERG (WST)
     * BARSINGHAUSEN-HOHENBOST.
     * BARTH (AWST)
     * BARUTH (AWST)
     * KUBSCHUETZ,KR.BAUTZEN
     * HEINERSREUTH-VOLLHOF
     * OBERZENT-BEERFELDEN
     * BELM
     * BERGZABERN,BAD
     * BERKA,BAD (FLUGPLATZ)
     * BERLEBURG,BAD-STUENZEL
     * BERLIN-BUCH
     * BERLIN-DAHLEM (MET.INST)
     * BERLIN-MARZAHN
     * BERLIN-BRANDENBURG
     * BERLIN-TEGEL (FLUGWEWA)
     * BERLIN-TEMP. (WST)
     * BERNBURG/SAALE (NORD)
     * BERUS (AWST)
     * BLANKENRATH
     * BOIZENBURG (WST)
     * BOLTENHAGEN (WST)
     * KOENIGSWINTER-HEIDERHOF
     * BORKEN I.W.
     * BRAUNLAGE (AWST)
     * BRAUNSCHWEIG-VOEL.(WST)
     * BREMEN (FLUGWEWA)
     * BREMERHAVEN (WST)
     * BREMERVOERDE (AWST)
     * BROCKEN (WEWA)
     * BUCHEN,KR.NECKAR-ODW.
     * BUCHENBACH
     * ROSENGARTEN-KLECKEN
     * BUECHEL (BW)
     * BUECKEBURG (BW)
     * BURGWALD-BOTTENDORF
     * CARLSFELD (AWST)
     * CELLE-WIETZENBRUCH (BW)
     * CHEMNITZ (WEWA)
     * CHIEMING (WST)
     * LAUTERTAL-OBERLAU.(AWST)
     * COTTBUS (WEWA)
     * CUXHAVEN (WEWA)
     * DACHWIG
     * DARMSTADT
     * DEUSELBACH
     * DIEPHOLZ(WEWA)
     * DILLENBURG
     * DILLINGEN/DONAU-FRISTIN.
     * DIPPOLDISWALDE-REINBERG
     * DOBERLUG-KIRCHHAIN(AWST)
     * DRESDEN-KLOTZ.(FLUGWEWA)
     * DRESDEN-HOSTERWITZ
     * DRESDEN-STREHLEN
     * DREWITZ,BEI BURG
     * DUERKHEIM,BAD
     * DUESSELDORF (FLUGWEWA)
     * EBERSBERG-HALBING
     * EBRACH
     * EICHSTAETT-LANDERSHOFEN
     * ELLWANGEN-RINDELBACH
     * ELPERSBUETTEL (AWST)
     * ELSTER,BAD-SOHL
     * ELZACH-FISNACHT
     * EMMENDINGEN-MUNDINGEN
     * ENNIGERLOH-OSTENFELDE
     * MUENCHEN-FLUGHAFEN
     * ERFDE
     * ERFURT-WEIMAR
     * MOEHRENDORF-KLEINSEEBACH
     * ESCHWEGE
     * ESLOHE
     * ESSEN-BREDENEY (AWST)
     * WEILERSWIST-LOMMERSUM
     * FALKENBERG,KR.ROTTAL-INN
     * FASSBERG (BW)
     * FELDBERG/SCHW. (WEWA)
     * FICHTELB./OFR-HUETTSTADL
     * FICHTELBERG (WEWA)
     * BIRX/RHOEN
     * FRANKFURT/M. (FLUGWEWA)
     * FRANKFURT/MAIN-WESTEND
     * FREIBURG I.BR. (AWST)
     * FREIBURG/ELBE
     * FREUDENSTADT (WEWA)
     * FRITZLAR (BW)
     * FULDA-HORAS
     * GARDELEGEN (WST)
     * GARMISCH-PARTENK. (AWST)
     * GEISENHEIM (AMBF)
     * GEISINGEN
     * GELBELSEE (AWST)
     * GELDERN-WALBECK
     * OHLSBACH
     * GENTHIN (AWST)
     * GERA-LEUMNITZ (WEWA)
     * GIESSEN/WETTENB. (WST)
     * GILSERBERG-MOISCHEID
     * GLUECKSBURG-MEIERWIK(BW)
     * GOERLITZ (WEWA)
     * GOETTINGEN (WEWA)
     * GOLDBERG (AWST)
     * GRAEFENBERG-KASBERG
     * GRAINET-REHBERG
     * GRAMBEK
     * GREIFSWALD (WEWA)
     * GREIFSWALDER OIE (AWST)
     * MUENSTER/OSNABRUECK
     * GROSS BERSSEN
     * GROSS LUESEWITZ
     * GROSSER ARBER (WEWA)
     * GRUENDAU-BREITENBORN
     * GRUENOW (AWST)
     * GUENZBURG
     * OLSDORF
     * HAMBURG-FUHLS.(FLUGWEWA)
     * HAMBURG-NEUWIEDENTHAL
     * HANNOVER-LANG.(FLUGWEWA)
     * HARBURG RIES (AWST)
     * HARZBURG,BAD
     * HARZGERODE (AWST)
     * HECHINGEN
     * HEINSBERG-SCHLEIDEN
     * HELGOLAND (WEWA)
     * HERSFELD,BAD (WST)
     * HERZBERG
     * HIDDENSEE-VITTE
     * HILGENROTH
     * BERTSDORF-HOERNITZ
     * HOF-HOHENSAAS (WEWA)
     * HOHENPEISSENBERG (OBS)
     * HOHN (BW)
     * HOHWACHT
     * HOLZDORF (BW)
     * HOLZKIRCHEN
     * BEVERN,KR.HOLZMINDEN
     * HUEMMERICH
     * IDAR-OBERSTEIN (BW)
     * INGOLSTADT (BW)
     * ITZEHOE (WST)
     * JAGEL (BW)
     * JENA (STERNWARTE)
     * KAHL/MAIN
     * KAHLER ASTEN (WEWA)
     * KAISERSBACH-CRONHUETTE
     * KAISERSLAUTERN
     * KALL-SISTIG
     * KEMPTEN (WST)
     * KIEL-HOLTENAU (BW)
     * KIRCHBERG/JAGST-HERBOLD.
     * KIRCHDORF/POEL
     * KISSINGEN,BAD (WEWA)
     * KITZINGEN
     * KL.FELDBERG/TS. (AWST)
     * KLEINER INSELSBERG
     * KLETTWITZ
     * KLEVE
     * KLIPPENECK (AWST)
     * KLITZSCHEN BEI TORGAU
     * KOELN-WAHN (FLUGWEWA)
     * KOENIGSHOFEN,BAD
     * KOESCHING
     * KOETHEN (ANHALT)
     * KOHLGRUB,BAD (ROSSHOF)
     * KONSTANZ (WEWA)
     * KRONACH
     * KUEMMERSBRUCK (BW)
     * KYRITZ (AWST)
     * LAAGE (BW)
     * LAHR (WEWA)
     * MERKLINGEN
     * LANGENLIPSDORF
     * LAUCHSTAEDT, BAD
     * LAUPHEIM (BW)
     * LECHFELD (BW)
     * LECK (AWST)
     * LEINEFELDE (WST)
     * LEIPZIG-HOLZHAUSEN(AWST)
     * LEIPZIG/HALLE
     * LENNESTADT-THETEN
     * LENZEN (ELBE)
     * LENZKIRCH-RUHBUEHL
     * LEUCHTTURM KIEL (AWST)
     * KOELN-STAMMHEIM
     * LICHTENHAIN-MITTE.(AWST)
     * LINDENBERG (OBS)
     * LIPPSPRINGE,BAD (WEWA)
     * LIPPSTADT-BOEKENFOERDE
     * LIST AUF SYLT (WST)
     * LOBENSTEIN, BAD
     * LOEHNBERG-OBERSHAUSEN
     * LUEBBEN-BLUMENFELDE
     * LUEBECK-BLANKENSEE(AWST)
     * LUECHOW (AWST)
     * LUEDENSCHEID (WEWA)
     * MAGDEBURG (WEWA)
     * MAINZ-LERCHENBERG (ZDF)
     * MANDERSCHEID-S.HOF
     * MANSCHNOW (WST)
     * COELBE, KR. MARBURG-B.
     * MARIENBERG (AWST)
     * MARIENBERG,BAD (WEWA)
     * MARNITZ (WEWA)
     * MARTINRODA
     * ASCHERSLEBEN-MEHRINGEN
     * MEININGEN (WEWA)
     * GARSEBACH BEI MEISSEN
     * MEMMINGEN
     * MEPPEN (BW)
     * MERGENTHEIM,BAD-NEUNKIR.
     * MESSSTETTEN-APPENTAL
     * METTEN
     * METZINGEN
     * MICHELSTADT
     * MICHELSTADT-VIELB.(WST)
     * SCHMIERITZ-WELTWITZ
     * MITTENWALD-BUCKELW.
     * ROELLBACH
     * MONTABAUR
     * MORINGEN-LUTTERBECK
     * MUEHLACKER (AWST)
     * MUEHLDORF/INN (WST)
     * MUENCHEBERG
     * MUENCHEN-STADT (WST)
     * MUENSINGEN-APFELSTETTEN
     * MUSKAU,BAD
     * NAUHEIM, BAD
     * NEUBURG/DONAU (BW)
     * NEUBURG/KAMMEL-LANGENHAS
     * NEUENAHR,BAD-AHRWEILER
     * MENZ
     * NEUHAUS A. RENNW.(WEWA)
     * NEUKIRCHEN-HAUPTSCHWENDA
     * NEUNK.-SEELSCH.-KRAWINK.
     * NEUNKIRCHEN-WELLESWEILER
     * NEUSTADT/KULM-FILCHENDF.
     * NIDEGGEN-SCHMIDT
     * NIEDERSTETTEN (BW)
     * NIENBURG
     * REIMLINGEN
     * NOERVENICH (BW)
     * NORDERNEY (WEWA)
     * NORDHOLZ (BW)
     * NUERBURG-BARWEILER(WEWA)
     * NUERNBERG-NETZSTALL
     * NUERNBERG-KRA.(FLUGWEWA)
     * KIEFERSFELDEN-GACH
     * OBERSTDORF (WEWA)
     * OBERSULM-WILLSBACH
     * OBERVIECHTACH
     * OEHRINGEN (WEWA)
     * OSCHATZ (WST)
     * OSTERFELD (AWST)
     * OSTHEIM V.D. RHOEN
     * OY-MITTELBERG-PETERSTHAL
     * PARSBERG/OPF.-EGLWANG
     * PELZERHAKEN (AWST)
     * PERL-NENNIG
     * PFORZHEIM-ISPRINGEN
     * PFULLENDORF
     * PIRMASENS
     * POMMELSBRUNN-MITTELBURG
     * POTSDAM (OBS)
     * PUTBUS (AWST)
     * QUEDLINBURG
     * QUERFURT-M.LODERSL.
     * QUICKBORN (AWST)
     * RAHDEN-KLEINENDORF
     * WEINGARTEN,KR.RAVENSBURG
     * REGENSBURG (WEWA)
     * REICHSHOF-ECKENHAGEN
     * RENNINGEN-IHINGER HOF
     * RHEINAU-MEMPRECHTSHOFEN
     * RHEINFELDEN
     * RHEINSTETTEN
     * ALTHEIM, KREIS BIBERACH
     * ROSENHEIM
     * ROSTOCK-WARNEM.(WEWA)
     * ROTENBURG (WUEMME)
     * ROTH
     * ROTHENBURG O.D.TAUBER
     * ROTTWEIL
     * KREUZNACH, BAD
     * RUPPERTSECKEN
     * SAARBRUECKEN-E(FLUGWEWA)
     * SACHSENHEIM
     * SALDENBURG-ENTSCHENREUTH
     * SALZUFLEN,BAD (AWST)
     * SANKT PETER-ORDING(WEWA)
     * SCHAAFHEIM-SCHLIERBACH
     * SCHIERKE
     * SCHLEIZ (AWST)
     * SCHLESWIG (WEWA)
     * SCHLUECHTERN-HEROLZ
     * SCHMUECKE (AWST)
     * SCHNEIFELFORSTHAUS
     * SCHOENWALD/OFR.-BRUNN
     * SCHORNDORF-KNOEBLING
     * SCHOTTEN
     * SCHWANDORF
     * SCHWARZBURG
     * SCHWERIN (WEWA)
     * SEEHAUSEN (WEWA)
     * SEESEN
     * SIGMARINGEN-LAIZ
     * SIGMARSZELL-ZEISERTSWEI.
     * SIMBACH/INN
     * SIMMERN-WAHLBACH
     * SOLTAU (AWST)
     * SONTRA
     * STAFFELSTEIN,BAD-STUBLNG
     * STEINAU,KR.CUXHAVEN
     * MITTELNKIRCHEN-HOHENFELD
     * OBERHARZ BROCKEN STIEGE
     * STOETTEN (WEWA)
     * WAGERSROTT
     * STRAUBING (AWST)
     * STUTTGART(SCHNAR.AWST)
     * STUTTGART-ECH.(FLUGWEWA)
     * TANN/RHOEN
     * TEGKWITZ
     * TETEROW (AWST)
     * WORPSWEDE-HUETTENBUSCH
     * TEUSCHNITZ
     * THOLEY (AWST)
     * TIRSCHENREUTH-LODERM.
     * TOENISVORST
     * TRIBSEES
     * TRIER-ZEWEN
     * TRIER-PETRISBERG (WEWA)
     * TROLLENHAGEN
     * TROSTBERG
     * TWISTETAL-MUEHLHAUSEN
     * UECKERMUENDE (AWST)
     * UELZEN
     * GOLLHOFEN
     * UMMENDORF (AWST)
     * VILLINGEN-SCHWENNINGEN
     * WAGHAEUSEL-KIRRLACH
     * WESERTAL-LIPPOLDSBERG
     * WITTENBORN
     * WALDEMS-REINBORN
     * WALTERSHAUSEN
     * WARBURG (AWST)
     * WAREN (MUERITZ)
     * WASSERKUPPE (WEWA)
     * WEIDEN/OPF. (WST)
     * WEIHENSTEPHAN (WST)
     * WEIMAR-SCHOENDORF
     * WEINBIET (AWST)
     * WEISKIRCHEN/SAAR
     * WEISSENBURG/BAY. (WST)
     * WERL (AWST)
     * WERNIGERODE (AWST)
     * FEHMARN (WEWA)
     * WIELENBACH (DEMOLLSTR.)
     * WIESBADEN-AURINGEN
     * WIESENBURG (WEWA)
     * NEUBULACH-OBERHAUGSTETT
     * WITTENBERG (WST)
     * WITTMUNDHAFEN (BW)
     * WITTSTOCK-ROTE MUEHLE
     * WOLFACH
     * WOLFSBURG (SUEDWEST)
     * DACHSBERG-WOLPADINGEN
     * WORMS
     * WUERZBURG (WEWA)
     * WUNSTORF (BW)
     * WUPPERTAL-BUCHENHOFEN
     * WUTOESCHINGEN-OFTERINGEN
     * ZEHDENICK
     * ZEITZ
     * ZINNWALD-GEORGEN.(WEWA)
     * ZUGSPITZE (WEWA)
     * LICHTENTANNE
     * ZWIESEL (AWST)
     * BASSUM
     * BERGE
     * EMDEN (WEWA)
     * FUERSTENZELL (WEWA)
     * HAHN (WEWA)
     * MANNHEIM (WEWA)
     * SCHOENHAGEN/OSTSEE (WST)
     * REIT IM WINKL
     * WENDISCH EVERN
     * OSTENFELD(RENDSBURG)
     * GRAMBOW-SCHWENNENZ
     * SOHLAND/SPREE
     * WANGERLAND-HOOKSIEL
     * WEIDENB.-WEIHERSCHNEIDB.
     * DOERNICK (AWST)
     * COSCHEN
     * LUEGDE-PAENBRUCH (AWST)
     * STEINHAGEN-NEGAST
     * SAARBRUECKEN-BURBACH
     * FRIEDRICHSHAFEN-UNTERRAD
     * GROSSERLACH-MANNENWEILER
     * INGELFINGEN-STACHENHAUS.
     * SCHWAEB. GMUEND-WEILER
     * SINGEN
     * BRILON-THUELEN
     * WUSTERWITZ
     * HUY-PABSTORF
     * MOORGRUND-GRAEFENDORF-N.
     * DEMKER
     * NOTZINGEN
     * MUEHLHAUSEN-GOERMAR
     * KARLSHAGEN
     * NOSSEN
     * LOHR/MAIN-HALSBACH
     * LUEDINGHAUSEN-BROCHTRUP
     * RUNKEL-ENNERICH
     * MAISACH-GALGEN
     * SCHONUNGEN-MAINBERG
     * ELSENDORF-HORNECK
     * LIEBENBURG-OTHFRESEN
     * SIEGSDORF-HOELL
     * BIELEFELD-DEPPENDORF
     * FREUDENBERG/MAIN-BOXTAL
     * HATTSTEDT
     * DONAUWOERTH-OSTERWEILER
     * OLBERSLEBEN
     * TREUEN
     * ARNSBERG-NEHEIM
     * HERMARINGEN-ALLEWIND
     * OFFENBACH-WETTERPARK
     * DEUTSCHNEUDORF-BRUEDERW.
     * PRACKENBACH-NEUHAEUSL
     * FELDBERG/MECKLENBURG
     * JESSNITZ
     * ALFELD (AWST)
     * EISENACH (AWST)
     * FEUCHTWANGEN-HEIL.(AWST)
     * WALDMUENCHEN (AWST)
     * BORKUM-FLUGPLATZ
     * AHAUS(AWST)
     * HECKELBERG
     * HOYERSWERDA (WST)
     * WUNSIEDEL-SCHOENB.(AWST)
     * GOTTFRIEDING (AWST)
     * HOHERODSKOPF-VB (WST)
     * LEUTKIRCH-HERLAZ.(AWST)
     * NEU-ULRICHSTEIN
     * NEUHUETTEN/SPESSART(AWST
     * LANGENWETZENDORF-GOETT.
     * KREIPITZSCH
     * PIDING
     * PADENSTEDT (PONY-PARK)
     * VEILSDORF
     * OBERHACHING-LAUFZORN
     * WITTINGEN-VORHOP
     * DUISBURG-BAERL
     * WAIBSTADT (AWST)
     * HAMELN-HASTENBECK
     * WALTROP-ABDINGHOF
     * GEVELSBERG-OBERBR.
     * LANDSHUT-REITHOF
     * ROCKENDORF
     * MEINERZHAGEN-REDLENDORF
     * HELMSTEDT-EMMERSTEDT
     * BALINGEN-BRONNHAUPTEN
     * AACHEN-ORSBACH
     * SCHAUENBURG-ELGERSHAUSEN
     * ULM-MAEHRINGEN
     * KAUFBEUREN-OBERBEUREN
     * HASENKRUG-HARDEBEK
     * WACKEN
     *
     */
}
