package org.jevis.commons.driver.dwd;

public enum Attribute {
    AIR_TEMPERATURE, ALL, CLOUDINESS, CLOUD_TYPE, DEW_POINT, EXTREME_TEMPERATURE, EXTREME_WIND, MOISTURE, PRECIPITATION, PRESSURE, SOIL, SOIL_TEMPERATURE, SOLAR, SUN, VISIBILITY, WEATHER_PHENOMENA, WIND


}
